export interface StatisticsSection {
  title: string;
  items: { code: string; label: string }[];
  headerColor?: string;
}

export const STATISTICS_SECTIONS: StatisticsSection[] = [
  {
    title: 'ESTADÍSTICA GENERAL / NOVEDADES',
    headerColor: 'bg-blue-500/20 dark:bg-blue-500/30',
    items: [
      { code: '1', label: 'REPORTES DEL VEN 9-1-1' },
      { code: '1.2', label: 'LLAMADAS DE EMERGENCIAS' },
      { code: '2', label: 'ACCIDENTES DE TRÁNSITO URBANOS' },
      { code: '2.1', label: 'COLISIÓN VEHÍCULO-MOTO' },
      { code: '2.2', label: 'COLISIÓN VEHÍCULO-VEHÍCULO' },
      { code: '2.3', label: 'COLISIÓN MOTO-MOTO' },
      { code: '2.4', label: 'COLISIÓN VEHÍCULO-OBJETO FIJO' },
      { code: '2.5', label: 'COLISIÓN MOTO-OBJETO FIJO' },
      { code: '2.6', label: 'DERRAPE' },
      { code: '2.7', label: 'COLISIÓN MULTIPLE' },
      { code: '2.8', label: 'ARROLLAMIENTO' },
      { code: '2.9', label: 'VOLCAMIENTO' },
      { code: '3', label: 'ACCIDENTES DE TRÁNSITO EXTRA URBANOS' },
      { code: '3.1', label: 'COLISIÓN VEHÍCULO-MOTO' },
      { code: '3.2', label: 'COLISIÓN VEHÍCULO-VEHÍCULO' },
      { code: '3.3', label: 'COLISIÓN MOTO-MOTO' },
      { code: '3.4', label: 'COLISIÓN VEHÍCULO-OBJETO FIJO' },
      { code: '3.5', label: 'COLISIÓN MOTO-OBJETO FIJO' },
      { code: '3.6', label: 'DERRAPE' },
      { code: '3.7', label: 'COLISIÓN MULTIPLE' },
      { code: '3.8', label: 'ARROLLAMIENTO' },
      { code: '3.9', label: 'VOLCAMIENTO' },
      { code: '3.10', label: 'LESIONADOS EN ACCIDENTES DE TRÁNSITO URBANOS' },
      { code: '3.11', label: 'LESIONADOS EN ACCIDENTES DE TRÁNSITO EXTRA URBANOS' },
      { code: '3.12', label: 'RESCATADOS EN ACCIDENTES DE TRÁNSITO URBANOS Y EXTRA URBANOS' },
      { code: '4', label: 'FALLECIDOS EN ACCIDENTES DE TRÁNSITO' },
      { code: '4.1', label: 'FALLECIDOS POR CAUSAS NATURALES' },
      { code: '4.2', label: 'FALLECIDOS POR CAUSAS DESCONOCIDAS' },
      { code: '4.3', label: 'FALLECIDOS POR ARMA DE FUEGO' },
      { code: '4.4', label: 'FALLECIDOS POR ARMA BLANCA' },
      { code: '4.5', label: 'HERIDOS POR ARMA BLANCA' },
      { code: '4.6', label: 'HERIDOS POR ARMA FUEGO' },
      { code: '4.7', label: 'LESIONADO POR ELECTROCUCION' },
      { code: '4.8', label: 'FALLECIDO POR ELECTRUCUCION' },
      { code: '5', label: 'ATENCIONES AL PÚBLICO' },
      { code: '5.1', label: 'ATENCIONES PREHOSPITALARIAS' },
      { code: '5.2', label: 'EN TRASLADOS' },
      { code: '5.3', label: 'EN RESIDENCIA' },
      { code: '5.4', label: 'EN SALA DE RADIO' },
      { code: '5.5', label: 'EN VÍA / LUGAR PÚBLICO' },
      { code: '5.6', label: 'EN INSTITUCION / COMERCIO' },
      { code: '5.7', label: 'EN GUARDIAS PREVENTIVAS' },
      { code: '6', label: 'SOLICITUDES DE TRASLADOS' },
      { code: '6.1', label: 'TRASLADOS URBANOS' },
      { code: '6.2', label: 'TRASLADOS EXTRAURBANOS' },
      { code: '6.3', label: 'DE CENTROS ASISTENCIALES A CENTROS ASISTENCIALES' },
      { code: '6.4', label: 'DE CENTROS ASISTENCIALES A RESIDENCIAS' },
      { code: '6.5', label: 'DE RESIDENCIAS A CENTROS ASISTENCIALES' },
      { code: '6.6', label: 'DE VÍA A CENTROS ASISTENCIALES' },
      { code: '6.7', label: 'DE SEDE A CENTROS ASISTENCIALES' },
      { code: '6.8', label: 'DE INSTITUCION / COMERCIO A CENTROS ASISTENCIALES' },
      { code: '6.9', label: 'DE RESIDENCIAS A RESIDENCIAS' },
      { code: '6.10', label: 'DE LUGAR PÚBLICO / VÍA A RESIDENCIAS' },
      { code: '7', label: 'GUARDIAS PREVENTIVAS' },
      { code: '7.1', label: 'DESPLIEGUES DE SEGURIDAD' },
      { code: '7.2', label: 'PUNTOS DE PREVENCIÓN' },
      { code: '7.3', label: 'PUNTOS EN SANTUARIO' },
      { code: '7.4', label: 'PUNTOS EN BALNEARIO' },
      { code: '7.5', label: 'RECORRIDOS PREVENTIVOS' },
      { code: '7.6', label: 'EVENTOS DEPORTIVOS' },
      { code: '7.7', label: 'EVENTOS ESPECIALES' },
      { code: '7.8', label: 'EVENTOS EN LUGAR PUBLICO Y / O PRIVADO' },
      { code: '8', label: 'APOYO A OTRAS INSTITUCIONES' },
      { code: '8.1', label: 'APOYOS SOCIALES' },
      { code: '8.2', label: 'APOYOS INSTITUCIONALES' },
      { code: '9', label: 'FUMIGACIONES' },
      { code: '9.1', label: 'INSTITUCIONES PÚBLICAS' },
      { code: '9.2', label: 'EMPRESAS PRIVADAS' },
      { code: '9.3', label: 'UNIDADES EDUCATIVAS' },
      { code: '9.4', label: 'CENTROS CULTURALES Y/O DEPORTIVOS' },
      { code: '9.5', label: 'CENTROS MÉDICOS' },
      { code: '9.6', label: 'CASAS/EDIFICIOS' },
      { code: '10', label: 'NIÑOS EXTRAVIADOS Y/O RECUPERADOS' },
      { code: '11', label: 'OPERACIÓN SAR' },
      { code: '11.1', label: 'RESCATADOS EN OPERACIÓN SAR' },
      { code: '11.2', label: 'RECUPERACIÓN DE CADÁVER EN OPERACIÓN SAR' },
      { code: '12', label: 'AUXILIO VIAL' },
      { code: '13', label: 'FALLAS DEL SERVICIO ELÉCTRICO' },
      { code: '14', label: 'FALLAS DEL SERVICIO DE COMUNICACIONES' },
      { code: '15', label: 'EVENTOS METEREOLÓGICOS' },
      { code: '16', label: 'INCENDIOS' },
      { code: '16.1', label: 'CONATOS DE INCENDIO' },
      { code: '16.2', label: 'INCENDIOS DE VIVIENDA' },
      { code: '16.3', label: 'INCENDIOS DE COMERCIO' },
      { code: '16.4', label: 'INCENDIOS DE DESECHOS' },
      { code: '16.5', label: 'INCENDIOS DE EDIFICIOS RESIDENCIALES' },
      { code: '16.6', label: 'INCENDIOS INDUSTRIALES' },
      { code: '16.7', label: 'INCENDIOS DE VEGETACIÓN' },
      { code: '16.8', label: 'INCENDIOS FORESTALES' },
      { code: '16.9', label: 'INCENDIOS ESTRUCTURALES' },
      { code: '16.10', label: 'INCENDIOS VEHICULARES' },
      { code: '16.11', label: 'INCENDIOS DE EMBARCACIONES' },
      { code: '16.12', label: 'INCENDIOS DE HIDROCARBUROS' },
      { code: '16.13', label: 'INCENDIOS POR FUEGOS ARTIFICIALES' },
      { code: '16.14', label: 'LESIONADOS EN INCENDIOS' },
      { code: '16.15', label: 'FALLECIDOS EN INCENDIOS' },
      { code: '17', label: 'MITIGACIONES DE RIESGOS' },
      { code: '17.1', label: 'PODA DE ÁRBOLES' },
      { code: '17.2', label: 'TALA DE ÁRBOLES' },
      { code: '17.3', label: 'FUGA DE GAS' },
      { code: '17.4', label: 'REMOCIÓN DE ESCOMBROS' },
      { code: '17.5', label: 'DERRAME DE HIDROCARBUROS (CONTENCIÓN)' },
      { code: '17.6', label: 'REUBICACIÓN DE AVISPAS / ABEJAS' },
      { code: '17.7', label: 'RESCATE Y/O REUBICACIÓN DE FAUNA SILVESTRE' },
    ],
  },
  {
    title: 'INSPECCIONES DE RIESGOS',
    headerColor: 'bg-green-600/20 dark:bg-green-600/30',
    items: [
      { code: '1', label: 'SOLICITUDES DE INSPECCIONES' },
      { code: '2', label: 'EVALUACIÓN DE DAÑOS Y ANÁLISIS DE NECESIDADES' },
      { code: '3', label: 'INSPECCIONES DE RIESGO' },
      { code: '3.1', label: 'DE ESTRUCTURA' },
      { code: '3.2', label: 'DE VIVIENDA' },
      { code: '3.3', label: 'DE PLANTELES EDUCATIVOS' },
      { code: '3.4', label: 'DE PLANTELES DEPORTIVOS' },
      { code: '3.5', label: 'DE INSTITUCIONES DE SALUD' },
      { code: '3.6', label: 'DE CENTRO COMERCIALES' },
      { code: '3.7', label: 'DE SANTUARIOS' },
      { code: '3.8', label: 'DE VIALIDAD' },
      { code: '3.9', label: 'DE PUENTES' },
      { code: '3.10', label: 'DE POSTES / ALUMBRADO' },
      { code: '3.11', label: 'DE TERMINAL MARITIMO' },
      { code: '3.12', label: 'DE AREAS DE RECREACION / PARQUES / PLAZAS' },
      { code: '3.13', label: 'DE ALJIBES / LAGUNA / QUEBRADA / RIO' },
      { code: '3.14', label: 'DE TANQUES DE ALMACENAMIENTO' },
      { code: '3.15', label: 'DE TERRENO' },
      { code: '3.16', label: 'DE MURO' },
      { code: '3.17', label: 'DE ÁRBOL' },
      { code: '3.18', label: 'DE DRENAJES' },
      { code: '3.19', label: 'DE BALNEARIOS' },
      { code: '3.20', label: 'DE COLMENA DE ABEJAS' },
      { code: '3.21', label: 'DE CAMPO' },
      { code: '4', label: 'SINIESTROS' },
      { code: '4.1', label: 'ANEGACIONES' },
      { code: '4.2', label: 'DESLIZAMIENTOS / DERRUMBES' },
      { code: '4.3', label: 'COLAPSO DE ESTRUCTURA' },
      { code: '4.4', label: 'LESIONADOS POR COLAPSO DE ESTRUCTURA' },
      { code: '4.5', label: 'FALLECIDOS POR COLAPSO DE ESTRUCTURA' },
      { code: '5', label: 'INFORMES REALIZADOS' },
      { code: '6', label: 'INFORMES ENTREGADOS' },
    ],
  },
  {
    title: 'ACCIDENTES Y RESCATES (MONTAÑA - ACUÁTICOS - AÉREOS)',
    headerColor: 'bg-red-600/20 dark:bg-red-600/30',
    items: [
      { code: '1', label: 'ACCIDENTES EN MONTAÑA' },
      { code: '1.1', label: 'LESIONADOS ACCIDENTE EN MONTAÑA' },
      { code: '1.2', label: 'FALLECIDOS ACCIDENTE MONTAÑA' },
      { code: '1.3', label: 'SALVADOS ACCIDENTE MONTAÑA' },
      { code: '1.4', label: 'DESAPARECIDOS ACT. MONTAÑA' },
      { code: '2.1', label: 'FALLECIDOS INMERSION' },
      { code: '3', label: 'SALVADOS INMERSION' },
      { code: '3.1', label: 'ACCIDENTES ACUATICOS' },
      { code: '3.2', label: 'LESIONADOS ACCIDENTES ACUATICOS' },
      { code: '3.3', label: 'SALVADOS ACCIDENTES ACUATICOS' },
      { code: '3.4', label: 'FALLECIDOS ACCIDENTES ACUATICOS' },
      { code: '4', label: 'ACCIDENTES AEREOS' },
      { code: '4.1', label: 'LESIONADOS ACCIDENTES AEREOS' },
      { code: '4.2', label: 'SALVADOS ACCIDENTES AEREOS' },
      { code: '4.3', label: 'FALLECIDOS ACCIDENTES AEREOS' },
    ],
  },
  {
    title: 'CAPACITACIÓN Y PREVENCIÓN',
    headerColor: 'bg-amber-500/20 dark:bg-amber-500/30',
    items: [
      { code: '1', label: 'CONVERSATORIOS (CONCIENTIZACIÓN EN PUESTOS DE ATENCIÓN)' },
      { code: '2', label: 'CAPACITACIONES' },
      { code: '2.1', label: 'A COMUNIDADES EDUCATIVAS' },
      { code: '2.2', label: 'A COMUNIDADES EN GENERAL' },
      { code: '2.3', label: 'A EMPRESAS PRIVADAS' },
      { code: '2.4', label: 'A VOLUNTARIOS Y FUNCIONARIOS' },
      { code: '2.5', label: 'A ORGANISMOS PUBLICOS' },
      { code: '3', label: 'PARTICIPANTES EN CAPACITACIONES' },
      { code: '3.1', label: 'EN COMUNIDADES EDUCATIVAS' },
      { code: '3.2', label: 'EN COMUNIDADES EN GENERAL' },
      { code: '3.3', label: 'EN EMPRESAS PRIVADAS' },
      { code: '3.4', label: 'VOLUNTARIOS Y FUNCIONARIOS' },
      { code: '3.5', label: 'EN ORGANISMOS PUBLICOS' },
      { code: '3.6', label: 'CONCIENTIZACIÓN VIAL' },
      { code: '3.7', label: 'ABORDAJES PREVENTIVOS' },
      { code: '4', label: 'SIMULACROS' },
      { code: '4.1', label: 'EN COMUNIDADES EDUCATIVAS' },
      { code: '4.2', label: 'EN COMUNIDAD GENERAL' },
      { code: '4.3', label: 'EN EMPRESAS PUBLICAS O PRIVADAS' },
      { code: '5', label: 'PARTICIPANTES EN SIMULACROS' },
      { code: '5.1', label: 'EN COMUNIDADES EDUCATIVAS' },
      { code: '5.2', label: 'EN COMUNIDAD GENERAL' },
      { code: '5.3', label: 'EN EMPRESAS PUBLICAS O PRIVADAS' },
      { code: '6', label: 'REUNIONES DE COORDINACION' },
      { code: '6.1', label: 'EN COMUNIDADES EDUCATIVAS' },
      { code: '6.2', label: 'EN COMUNIDADES EN GENERAL' },
      { code: '6.3', label: 'EN ORGANISMOS PUBLICOS' },
      { code: '6.4', label: 'EN EMPRESAS PRIVADAS' },
      { code: '6.5', label: 'CON VOLUNTARIOS' },
    ],
  },
];

export const DEFAULT_STATISTICS_CATEGORIES = STATISTICS_SECTIONS.flatMap((section) =>
  section.items.map((item) => `${item.code} ${item.label}`)
);
